enum ACTION {
  UPD_LOGIN_FORM = "UPD_LOGIN_FORM",

  LOGIN = "LOGIN",
  LOGOUT = "LOGOUT",

  DID_SET_USER = "DID_SET_USER",
  SET_USER = "SET_USER",

  REFRESH_TOKEN = "REFRESH_TOKEN",
  SET_ACCESS_TOKEN = "SET_ACCESS_TOKEN",

  UPD_FILTER = "UPD_FILTER",

  SET_OPTION = "SET_OPTION",

  GET_CATEGORIES = "GET_CATEGORIES",
  SET_CATEGORIES = "SET_CATEGORIES",
  POST_CATEGORY = "POST_CATEGORY",
  SET_CATEGORY = "SET_CATEGORY",
  DELETE_CATEGORY = "DELETE_CATEGORY",
  SELECT_CATEGORY = "SELECT_CATEGORY",

  GET_PRODUCTS = "GET_PRODUCTS",
  SET_PRODUCTS = "SET_PRODUCTS",
  POST_PRODUCT = "POST_PRODUCT",
  PUT_PRODUCT = "PUT_PRODUCT",
  SET_PRODUCT = "SET_PRODUCT",
  DELETE_PRODUCT = "DELETE_PRODUCT",

  UPD_NUM_OF_ROWS = "UPD_NUM_OF_ROWS",
  UPD_PRODUCT_FORM = "UPD_PRODUCT_FORM",
  UPD_PRODUCT_FORM_TABLE = "UPD_PRODUCT_FORM_TABLE",

  ADD_TO_BAG = "ADD_TO_BAG",
  REMOVE_FROM_BAG = "REMOVE_FROM_BAG",
  POST_DEMAND = "POST_DEMAND",
  UPD_DEMAND_FORM = "UPD_DEMAND_FORM",
  GET_DEMANDS = "GET_DEMANDS",
  SET_DEMANDS = "SET_DEMANDS",

  ALERT = "ALERT",
  CLEAN_ALERT = "CLEAN_ALERT",
}

export default ACTION;
