enum ACTION {
  LOGIN = "LOGIN",
  LOGOUT = "LOGOUT",
  DID_SET_USER = "DID_SET_USER",
  SET_USER = "SET_USER",
  UPD_LOGIN_FORM = "UPD_LOGIN_FORM",

  UPD_FILTER = "UPD_FILTER",

  SET_OPTION = "SET_OPTION",

  GET_CATEGORIES = "GET_CATEGORIES",
  SET_CATEGORIES = "SET_CATEGORIES",
  POST_CATEGORY = "POST_CATEGORY",
  SET_CATEGORY = "SET_CATEGORY",
  DELETE_CATEGORY = "DELETE_CATEGORY",

  GET_PRODUCTS = "GET_PRODUCTS",
  SET_PRODUCTS = "SET_PRODUCTS",
  POST_PRODUCT = "POST_PRODUCT",
  SET_PRODUCT = "SET_PRODUCT",
  DELETE_PRODUCT = "DELETE_PRODUCT",

  UPD_NUM_OF_ROWS = "UPD_NUM_OF_ROWS",
  UPD_PRODUCT_FORM = "UPD_PRODUCT_FORM",
  UPD_PRODUCT_FORM_TABLE = "UPD_PRODUCT_FORM_TABLE",
}

export default ACTION;
